language: r
cache: packages

matrix:
  include:
    - os: linux
      r: devel
    - os: linux
      r: release
    #- os: osx
    #  osx_image: xcode12.2
    #- os: osx
    #  osx_image: xcode11.6
    #- os: osx
    #  osx_image: xcode10.3

r_packages:
  - data.table
  - dplyr
  - EML
  - emld
  - geosphere
  - ggplot2
  - httr
  - lubridate
  - magrittr
  - neonUtilities
  - rmarkdown
  - stringr
  - tidyr
  - tools
  - xml2
  - ritis
  - taxize
  - worrms
  
warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'
  
addons:
  apt:
    packages:
      - libv8-dev
      - libjq-dev
